const data = {
  "city": {
    "id": 94101,
    "city": "San Francisco",
    "lat": 37.78,
    "lon": -122.42,
    "state": "CA",
    "country": "us",
    "zip": "94101",
    "member_count": 60351
  },
  "events": [
    {
      "created": 1567569090000,
      "duration": 10800000,
      "id": "264542272",
      "name": "Howl-o-ween Block Pawty",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1570302000000,
      "local_date": "2019-10-05",
      "local_time": "12:00",
      "updated": 1567569090000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 9,
      "venue": {
        "id": 26608822,
        "name": "Paw Patch Pastries & Pet Boutique",
        "lat": 37.757469177246094,
        "lon": -122.39293670654297,
        "repinned": false,
        "address_1": "701 Pennsylvania Ave",
        "city": "San Francisco",
        "country": "us",
        "localized_country_name": "USA",
        "zip": "94107",
        "state": "CA"
      },
      "group": {
        "created": 1373660562000,
        "name": "SF Dog Connect Meetup",
        "id": 9329602,
        "join_mode": "open",
        "lat": 37.7400016784668,
        "lon": -122.44000244140625,
        "urlname": "SF-Dog-Connect-Meetup",
        "who": "SF Dog Connectors",
        "localized_location": "San Francisco, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/SF-Dog-Connect-Meetup/events/264542272/",
      "description": "<p>The spell has been cast .... Our Howl-o-ween block pawty is going to be a blast! Join the fun on Saturday, October 5th at the bewitching hour of 12:00 p.m. for Mischief, Mayhem, and Munchies! Let's Eat, Drink, and be Scary together!</p> <p>*Costume Contest!! Who is ready to compete! Prizes will be awarded to the winners! (open to dogs, and humans with dogs)</p> <p>*Best Dog Trick! Can your dog do an amazing dog trick for a treat? Show us what you got!</p> <p>*Trick-or-treating between vendors (for dogs &amp; kids)</p> <p>Check out who will be at the pawty below:</p> <p>Paw Patch Pastries - your pup will enjoy the most Boo-tastic treats this Halloween from doggie Sangria (non-alcoholic) to puppetizers! (pawpatchpastries.com)</p> <p>La Stazione Coffee + Wine Bar - Human munchies and spirits from our cozy neighborhood cafe/ wine bar! A neighborhood place with the atmosphere reminiscent of the typical caffes found in even the tiniest little towns dotting the Italian landscape.Their coffee is prepared to the most exacting standards of espresso-making, using the machinery designed and built in Italy",
        "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1569460230000,
      "duration": 7200000,
      "id": "265166172",
      "name": "Free Event - Fort Mason Community Garden, San Francisco",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1571583600000,
      "local_date": "2019-10-20",
      "local_time": "08:00",
      "updated": 1569460230000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 1,
      "venue": {
        "id": 26141254,
        "name": "Fort Mason Community Garden",
        "lat": 37.80598068237305,
        "lon": -122.4278564453125,
        "repinned": true,
        "address_1": "Pope Rd",
        "city": "San Francisco",
        "country": "us",
        "localized_country_name": "USA",
        "zip": "94109",
        "state": "CA"
      },
      "group": {
        "created": 1378828073000,
        "name": "Golden Gate Audubon - Free Birding Walks",
        "id": 10195652,
        "join_mode": "open",
        "lat": 37.869998931884766,
        "lon": -122.27999877929688,
        "urlname": "Golden-Gate-Audubon-Society",
        "who": "Members",
        "localized_location": "Berkeley, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/Golden-Gate-Audubon-Society/events/265166172/",
      "description": "<p>(Third Sunday bird walk)</p> <p>Meet in front of the Community Garden to explore several different habitats in this compact part of GGNRA. The focus will be looking for early migrants. The garden and the battery could have orioles, warblers, tanagers and flycatchers. We'll also scan Aquatic Park for shorebirds and water birds. Restroom in meadow, ample parking if there is no race on the waterfront (also easily accessible by transit). Most of the walk is flat, on mostly paved walkways, but there is one short steep descent to the waterfront. There are benches in the garden but nowhere else on the walk. Heavy rain cancels.",
        "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1268852112000,
      "id": "gzbdnyznbzb",
      "name": "The San Francisco English Bulldog Monthly Meetup",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1571508000000,
      "local_date": "2019-10-19",
      "local_time": "11:00",
      "updated": 1273504360000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 8,
      "group": {
        "created": 1045682815000,
        "name": "The San Francisco English Bulldog Meetup Group",
        "id": 54356,
        "join_mode": "open",
        "lat": 37.77000045776367,
        "lon": -122.44000244140625,
        "urlname": "sfbulldogs",
        "who": "SF Bulldoggers",
        "localized_location": "San Francisco, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/sfbulldogs/events/gzbdnyznbzb/",
      "description": "<p>Greetings SF Bulldoggers!</p> <p>The San Francisco English Bulldog Meetup is held at Crissy Field.<br/>Bring your bully to start the weekend off right and meet some great people at the beach.</p> <p>When you arrive at the beach, we'll be towards the left near the tidal marsh that flows into the ocean. It's technically called the the East Beach parking area. NOTE: It's not the North Parking area.</p> <p>Can't wait to see you at the meetup.</p> <p>Cheers!<br/>Lehua, Ryan, Poi Boy, and Bella</p> ",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1268852112000,
      "id": "gzbdnyzpbvb",
      "name": "The San Francisco English Bulldog Monthly Meetup",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1573930800000,
      "local_date": "2019-11-16",
      "local_time": "11:00",
      "updated": 1273504360000,
      "utc_offset": -28800000,
      "waitlist_count": 0,
      "yes_rsvp_count": 3,
      "group": {
        "created": 1045682815000,
        "name": "The San Francisco English Bulldog Meetup Group",
        "id": 54356,
        "join_mode": "open",
        "lat": 37.77000045776367,
        "lon": -122.44000244140625,
        "urlname": "sfbulldogs",
        "who": "SF Bulldoggers",
        "localized_location": "San Francisco, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/sfbulldogs/events/gzbdnyzpbvb/",
      "description": "<p>Greetings SF Bulldoggers!</p> <p>The San Francisco English Bulldog Meetup is held at Crissy Field.<br/>Bring your bully to start the weekend off right and meet some great people at the beach.</p> <p>When you arrive at the beach, we'll be towards the left near the tidal marsh that flows into the ocean. It's technically called the the East Beach parking area. NOTE: It's not the North Parking area.</p> <p>Can't wait to see you at the meetup.</p> <p>Cheers!<br/>Lehua, Ryan, Poi Boy, and Bella</p> ",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1268852112000,
      "id": "gzbdnyzqbcc",
      "name": "The San Francisco English Bulldog Monthly Meetup",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1576954800000,
      "local_date": "2019-12-21",
      "local_time": "11:00",
      "updated": 1273504360000,
      "utc_offset": -28800000,
      "waitlist_count": 0,
      "yes_rsvp_count": 2,
      "group": {
        "created": 1045682815000,
        "name": "The San Francisco English Bulldog Meetup Group",
        "id": 54356,
        "join_mode": "open",
        "lat": 37.77000045776367,
        "lon": -122.44000244140625,
        "urlname": "sfbulldogs",
        "who": "SF Bulldoggers",
        "localized_location": "San Francisco, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/sfbulldogs/events/gzbdnyzqbcc/",
      "description": "<p>Greetings SF Bulldoggers!</p> <p>The San Francisco English Bulldog Meetup is held at Crissy Field.<br/>Bring your bully to start the weekend off right and meet some great people at the beach.</p> <p>When you arrive at the beach, we'll be towards the left near the tidal marsh that flows into the ocean. It's technically called the the East Beach parking area. NOTE: It's not the North Parking area.</p> <p>Can't wait to see you at the meetup.</p> <p>Cheers!<br/>Lehua, Ryan, Poi Boy, and Bella</p> ",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1307201907000,
      "id": "cpctsyznbhb",
      "name": "SF Boxer/ SuperDog City Mania!!! Monthly Meetup",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1570298400000,
      "local_date": "2019-10-05",
      "local_time": "11:00",
      "updated": 1449153094000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 1,
      "venue": {
        "id": 608435,
        "name": "Crissy Field",
        "lat": 37.80595397949219,
        "lon": -122.44940948486328,
        "repinned": false,
        "address_1": "First parking lot off Mason St ",
        "address_2": "East Parking Lot, North end of the Presidio",
        "city": "San Francisco",
        "country": "us",
        "localized_country_name": "USA",
        "phone": "(415) 561-4323",
        "zip": "94102",
        "state": "CA"
      },
      "group": {
        "created": 1244044829000,
        "name": "SF Boxer/ SuperDogCity.com Mania!!!",
        "id": 1466044,
        "join_mode": "open",
        "lat": 37.790000915527344,
        "lon": -122.41999816894531,
        "urlname": "SF-Superdogcity",
        "who": "members",
        "localized_location": "San Francisco, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/SF-Superdogcity/events/cpctsyznbhb/",
      "description": "<p>This will be SF Boxer Mania. Where we will host as many of our boxer- friends in one confined area along Crissy Field Beach. It will also present new opportunities to make new friends and social networks.</p> <p>PERSONAL GREETING FROM THE ORGANIZER/ SPONSOR:</p> <p>Welcome to our boxer meetup!  My name is Corey Vitale.  I wanted to send a special thank you, to all of you.  All of this wouldn't be possible without your support.   It's been a pleasure watching our boxer meetup grow to over 300 members the past 6 years, and still going strong!  I never would have imagined this, a dream come true!</p> <p>Im also the owner of SuperDogCity.com.   We are a professional dog walking and puppy care service with over 10 years of service.   Please visit our website for more information.   We have the most boxers in our dog walking company than any other SF competitor.   Please ask about our 1-hour group playtimes to SF beaches and parks!</p> ",
    "how_to_find_us": "You'll see and hear all of the boxers running along the beach!",
    "visibility": "public",
    "member_pay_fee": false
},
  {
    "created": 1569370206000,
    "duration": 9000000,
    "id": "265134568",
    "name": "San Francisco Botanical Garden",
    "date_in_series_pattern": false,
    "status": "upcoming",
    "time": 1570374000000,
    "local_date": "2019-10-06",
    "local_time": "08:00",
    "updated": 1569370234000,
    "utc_offset": -25200000,
      "waitlist_count": 0,
        "yes_rsvp_count": 4,
          "venue": {
  "id": 26097911,
    "name": "San Francisco Botanical Garden",
      "lat": 37.76770782470703,
        "lon": -122.46931457519531,
          "repinned": false,
            "address_1": "1199 9th Ave",
              "city": "San Francisco",
                "country": "us",
                  "localized_country_name": "USA",
                    "zip": "94122",
                      "state": "CA"
},
"group": {
  "created": 1378828073000,
    "name": "Golden Gate Audubon - Free Birding Walks",
      "id": 10195652,
        "join_mode": "open",
          "lat": 37.869998931884766,
            "lon": -122.27999877929688,
              "urlname": "Golden-Gate-Audubon-Society",
                "who": "Members",
                  "localized_location": "Berkeley, CA",
                    "state": "CA",
                      "country": "us",
                        "region": "en_US",
                          "timezone": "US/Pacific"
},
"link": "https://www.meetup.com/Golden-Gate-Audubon-Society/events/265134568/",
  "description": "<p>(First Sunday bird walk; leaders vary by month)</p> <p>Meet at the front gate of the garden in Golden Gate Park, 9th Ave. at Lincoln Way. The garden has several micro-habitats that attract an array of resident, migrant, and vagrant birds. This monthly trip is oriented toward helping beginning birders develop their skills. Families with kids are encouraged. Parents, please respect the other birders and leave the walk if your child becomes a distraction. Entry is free before 9 a.m.</p> <p>Hosts: Rob Cullison, [masked]; Angie Geiger, [masked]; Ginny Marshall, [masked]</p> ",
    "visibility": "public",
      "member_pay_fee": false
},
{
  "created": 1563641250000,
    "duration": 7200000,
      "id": "ptpjfryznbbc",
        "name": "Mission Bay French Bulldog Meetup",
          "date_in_series_pattern": false,
            "status": "upcoming",
              "time": 1571592600000,
                "local_date": "2019-10-20",
                  "local_time": "10:30",
                    "updated": 1563641250000,
                      "utc_offset": -25200000,
                        "waitlist_count": 0,
                          "yes_rsvp_count": 6,
                            "venue": {
    "id": 26525716,
      "name": "New Mission Bay Dog Park",
        "lat": 37.77253723144531,
          "lon": -122.39396667480469,
            "repinned": false,
              "address_1": "57 El Dorado St ",
                "city": "San Francisco ",
                  "country": "us",
                    "localized_country_name": "USA",
                      "zip": "94158",
                        "state": "CA"
  },
  "group": {
    "created": 1262240897000,
      "name": "San Francisco French Bulldog Meetup",
        "id": 1575102,
          "join_mode": "open",
            "lat": 37.790000915527344,
              "lon": -122.41999816894531,
                "urlname": "French-Bulldog-Meetup",
                  "who": "Frenchie Enthusiasts/Parents",
                    "localized_location": "San Francisco, CA",
                      "state": "CA",
                        "country": "us",
                          "region": "en_US",
                            "timezone": "US/Pacific"
  },
  "link": "https://www.meetup.com/French-Bulldog-Meetup/events/ptpjfryznbbc/",
    "description": "<p>*UPDATE NEW LOCATION* Let's meet at 10:30 at the NEW Mission Bay dog park at 57 El Dorado st. This is a new park without the gravel so it should be better for our pups. attached is a link to the park<br/>",
  "visibility": "public",
    "member_pay_fee": false
},
{
  "created": 1563641250000,
    "duration": 7200000,
      "id": "ptpjfryzpbwb",
        "name": "Mission Bay French Bulldog Meetup",
          "date_in_series_pattern": false,
            "status": "upcoming",
              "time": 1574015400000,
                "local_date": "2019-11-17",
                  "local_time": "10:30",
                    "updated": 1563641250000,
                      "utc_offset": -28800000,
                        "waitlist_count": 0,
                          "yes_rsvp_count": 4,
                            "venue": {
    "id": 26525716,
      "name": "New Mission Bay Dog Park",
        "lat": 37.77253723144531,
          "lon": -122.39396667480469,
            "repinned": false,
              "address_1": "57 El Dorado St ",
                "city": "San Francisco ",
                  "country": "us",
                    "localized_country_name": "USA",
                      "zip": "94158",
                        "state": "CA"
  },
  "group": {
    "created": 1262240897000,
      "name": "San Francisco French Bulldog Meetup",
        "id": 1575102,
          "join_mode": "open",
            "lat": 37.790000915527344,
              "lon": -122.41999816894531,
                "urlname": "French-Bulldog-Meetup",
                  "who": "Frenchie Enthusiasts/Parents",
                    "localized_location": "San Francisco, CA",
                      "state": "CA",
                        "country": "us",
                          "region": "en_US",
                            "timezone": "US/Pacific"
  },
  "link": "https://www.meetup.com/French-Bulldog-Meetup/events/ptpjfryzpbwb/",
    "description": "<p>*UPDATE NEW LOCATION* Let's meet at 10:30 at the NEW Mission Bay dog park at 57 El Dorado st. This is a new park without the gravel so it should be better for our pups. attached is a link to the park<br/>",
  "visibility": "public",
    "member_pay_fee": false
},
{
  "created": 1569459671000,
    "duration": 7200000,
      "id": "265166059",
        "name": "Free Event - Corona Heights, San Francisco",
          "date_in_series_pattern": false,
            "status": "upcoming",
              "time": 1571410800000,
                "local_date": "2019-10-18",
                  "local_time": "08:00",
                    "updated": 1569459671000,
                      "utc_offset": -25200000,
                        "waitlist_count": 0,
                          "yes_rsvp_count": 2,
                            "venue": {
    "id": 26187431,
      "name": "Randall Museum",
        "lat": 37.76445007324219,
          "lon": -122.43817138671875,
            "repinned": false,
              "address_1": "199 Museum Way",
                "city": "San Francisco",
                  "country": "us",
                    "localized_country_name": "USA",
                      "zip": "94114",
                        "state": "CA"
  },
  "group": {
    "created": 1378828073000,
      "name": "Golden Gate Audubon - Free Birding Walks",
        "id": 10195652,
          "join_mode": "open",
            "lat": 37.869998931884766,
              "lon": -122.27999877929688,
                "urlname": "Golden-Gate-Audubon-Society",
                  "who": "Members",
                    "localized_location": "Berkeley, CA",
                      "state": "CA",
                        "country": "us",
                          "region": "en_US",
                            "timezone": "US/Pacific"
  },
  "link": "https://www.meetup.com/Golden-Gate-Audubon-Society/events/265166059/",
    "description": "<p>(Third Friday bird walk)</p> <p>Meet at the Randall Museum entrance gate. Trails are stable but steep and require navigating dirt paths with box step staircases; trails are single track for a short portion depending on the choice of route, and there are several places to sit throughout every route.</p> <p>Come for the walk and stay for the newly remodeled Randall Museum and Café Josephine. Free parking is available and transit options are good, with a bus along Roosevelt Way and MUNI trains just below on Market Street. Heavy rain cancels.",
  "visibility": "public",
    "member_pay_fee": false
},
{
  "created": 1525201081000,
    "duration": 3600000,
      "id": "xchvqpyznbkc",
        "name": "San Francisco Yorkie and Dog Friends Meetup",
          "date_in_series_pattern": false,
            "status": "upcoming",
              "time": 1572206400000,
                "local_date": "2019-10-27",
                  "local_time": "13:00",
                    "updated": 1525201081000,
                      "utc_offset": -25200000,
                        "waitlist_count": 0,
                          "yes_rsvp_count": 2,
                            "venue": {
    "id": 12031152,
      "name": "Moscone Recreation Center",
        "lat": 37.801265716552734,
          "lon": -122.43299102783203,
            "repinned": false,
              "address_1": "1800 Chestnut Street",
                "city": "San Francisco",
                  "country": "us",
                    "localized_country_name": "USA",
                      "zip": "94123",
                        "state": "CA"
  },
  "group": {
    "created": 1049407174000,
      "name": "San Francisco Yorkshire Terrier & Dog Friends Meetup Group",
        "id": 170014,
          "join_mode": "open",
            "lat": 37.79999923706055,
              "lon": -122.44000244140625,
                "urlname": "sfyorkiemeetup",
                  "who": "Yorkie Lovers",
                    "localized_location": "San Francisco, CA",
                      "state": "CA",
                        "country": "us",
                          "region": "en_US",
                            "timezone": "US/Pacific"
  },
  "link": "https://www.meetup.com/sfyorkiemeetup/events/xchvqpyznbkc/",
    "description": "<p>Hi All,</p> <p>The Moscone Dog Play Area is now opened and fenced for our four little friends to play! We haven't had a meetup for awhile, but please come by on Sunday, April 29th if you want to check out the new dog park and meet new and old friends. All dog breeds are welcome. WOOF forever!</p> ",
      "visibility": "public",
        "member_pay_fee": false
},
{
  "created": 1567549192000,
    "duration": 5400000,
      "id": "264533761",
        "name": "Dog Self Defense & Reading Dogs' Body Language. ",
          "rsvp_limit": 30,
            "date_in_series_pattern": false,
              "status": "upcoming",
                "time": 1573934400000,
                  "local_date": "2019-11-16",
                    "local_time": "12:00",
                      "updated": 1567667651000,
                        "utc_offset": -28800000,
                          "waitlist_count": 0,
                            "yes_rsvp_count": 23,
                              "venue": {
    "id": 26526104,
      "name": "George Christopher Playground",
        "lat": 37.74400329589844,
          "lon": -122.44025421142578,
            "repinned": false,
              "address_1": "5210 Diamond Heights Blvd",
                "city": "San Francisco",
                  "country": "us",
                    "localized_country_name": "USA",
                      "zip": "94131",
                        "state": "CA"
  },
  "group": {
    "created": 1373660562000,
      "name": "SF Dog Connect Meetup",
        "id": 9329602,
          "join_mode": "open",
            "lat": 37.7400016784668,
              "lon": -122.44000244140625,
                "urlname": "SF-Dog-Connect-Meetup",
                  "who": "SF Dog Connectors",
                    "localized_location": "San Francisco, CA",
                      "state": "CA",
                        "country": "us",
                          "region": "en_US",
                            "timezone": "US/Pacific"
  },
  "link": "https://www.meetup.com/SF-Dog-Connect-Meetup/events/264533761/",
    "description": "<p>NOTE: This meetup will be a little different than previous ones.</p> <p>As usual, a combination of all types of dogs are welcome: aggressive/reactive, shy/fearful, and curious/comfortable.</p> <p>But we will be using this Meetup to examine all of these different types of reactions to other dogs. The Pooch Coach will explain their body language, and how to read and understand it. We will get to see a wide variety of ways that dogs show their emotions.</p> <p>This will hopefully help people avoid confrontations in the future, and be better equipped to make judgments and decisions for their dog's and their own safety.</p> <p>In combination with this, The Pooch Coach will be demonstrating some self-defense moves for when aggressive dogs get too close, especially if they’re off leash.</p> <p>Please make sure and sign up for this, because we have to have at least 15 or 20 dogs to make it worthwhile.</p> <p>PLEASE NOTE THAT THE LOCATION MIGHT CHANGE DUE TO A REMODEL OF THE PARK BEGINNING SOMETIME IN THE FALL/WINTER. WE WILL KEEP YOU POSTED.<br/>----------------------------------------------------------</p>",
  "visibility": "public",
    "member_pay_fee": false
},
{
  "created": 1268852161000,
    "id": "wvcdnyznbjc",
      "name": "The San Francisco Shih Tzu Meetup Group Monthly Meetup",
        "date_in_series_pattern": false,
          "status": "upcoming",
            "time": 1572114600000,
              "local_date": "2019-10-26",
                "local_time": "11:30",
                  "updated": 1268852161000,
                    "utc_offset": -25200000,
                      "waitlist_count": 0,
                        "yes_rsvp_count": 4,
                          "group": {
    "created": 1049676248000,
      "name": "The San Francisco Shih Tzu Meetup Group",
        "id": 141141,
          "join_mode": "open",
            "lat": 37.779998779296875,
              "lon": -122.44000244140625,
                "urlname": "San-Francisco-ShihTzu-Meetup",
                  "who": "Shih Tzu Owners & Lovers",
                    "localized_location": "San Francisco, CA",
                      "state": "CA",
                        "country": "us",
                          "region": "en_US",
                            "timezone": "US/Pacific"
  },
  "link": "https://www.meetup.com/San-Francisco-ShihTzu-Meetup/events/wvcdnyznbjc/",
    "description": "<p>We will meet at the top of the hill at 11:30 AM - we stay and socialize for about an hour and then take a walk sometime between 12:15 and 12:30 depending on how many Shih Tzus and people are there......the walk is around the park on the walkway - if you are late, please look for us there....the walking time varies depending on how much talking, sniffing, exploring, sitting and all those other people and doggie things that are happening.<br/>See you there</p> ",
      "visibility": "public",
        "member_pay_fee": false
},
{
  "created": 1565809395000,
    "duration": 7200000,
      "id": "jvlqgryzmbmc",
        "name": "Sunday Evening Pet-Loss Video Chatroom",
          "date_in_series_pattern": false,
            "status": "upcoming",
              "time": 1569805200000,
                "local_date": "2019-09-29",
                  "local_time": "18:00",
                    "updated": 1565809395000,
                      "utc_offset": -25200000,
                        "waitlist_count": 0,
                          "yes_rsvp_count": 1,
                            "group": {
    "created": 1541692994000,
      "name": "Pet Loss Support Group",
        "id": 30485827,
          "join_mode": "open",
            "lat": 37.779998779296875,
              "lon": -122.44000244140625,
                "urlname": "petcloud-pet",
                  "who": "Members",
                    "localized_location": "San Francisco, CA",
                      "state": "CA",
                        "country": "us",
                          "region": "en_US",
                            "timezone": "US/Pacific"
  },
  "link": "https://www.meetup.com/petcloud-pet/events/jvlqgryzmbmc/",
    "description": "<p>Join us this Sunday Evening for our pet-loss video chatroom. Come share your story and listen to the stories of others who have lost and who are also grieving the loss of a beloved pet.</p> <p>First-time Guests are required to register beforehand. It's easy. Simply send us an email at [masked] and we'll be in touch shortly with additional details and the Google hangouts link (no software required!).</p> <p>Hope to see you there.</p> ",
      "visibility": "public",
        "member_pay_fee": false
},
{
  "local_time": "13:00",
    "local_date": "2019-10-12",
      "link": "https://www.meetup.com/playfuldoggysocial/events/vtlmjryznbqb/",
        "visibility": "public_limited",
          "group": {
    "created": 1346431185000,
      "name": "Active & Playful Small to Medium Size Doggy Social",
        "id": 4711602,
          "join_mode": "approval",
            "lat": 37.869998931884766,
              "lon": -122.52999877929688,
                "urlname": "playfuldoggysocial",
                  "who": "Woofers",
                    "localized_location": "Sausalito, CA",
                      "state": "CA",
                        "country": "us",
                          "region": "en_US",
                            "timezone": "US/Pacific"
  },
  "waitlist_count": 0,
    "yes_rsvp_count": 2,
      "duration": 7200000,
        "time": 1570910400000,
          "utc_offset": -25200000,
            "name": "Small Dogs Go for a Crissy Field Walk and Playtime!",
              "id": "vtlmjryznbqb"
},
{
  "created": 1566609717000,
    "duration": 7200000,
      "id": "rxrchryznbjb",
        "name": "Happy Halloween! The little goblins (AKA Chihuahuas) are ready to PARTAY!",
          "date_in_series_pattern": false,
            "status": "upcoming",
              "time": 1570388400000,
                "local_date": "2019-10-06",
                  "local_time": "12:00",
                    "updated": 1568738819000,
                      "utc_offset": -25200000,
                        "waitlist_count": 0,
                          "yes_rsvp_count": 15,
                            "venue": {
    "id": 739824,
      "name": "Stern Grove",
        "lat": 37.73569107055664,
          "lon": -122.48529052734375,
            "repinned": true,
              "address_1": "Vale Ave",
                "city": "San Francisco",
                  "country": "us",
                    "localized_country_name": "USA",
                      "phone": "Venue's phone number",
                        "zip": "94132",
                          "state": "CA"
  },
  "group": {
    "created": 1162579376000,
      "name": "San Francisco Chihuahua Meetup",
        "id": 358390,
          "join_mode": "approval",
            "lat": 37.7400016784668,
              "lon": -122.48999786376953,
                "urlname": "sfchihuahua",
                  "who": "Chihuahua & Small Dog Lovers",
                    "localized_location": "San Francisco, CA",
                      "state": "CA",
                        "country": "us",
                          "region": "en_US",
                            "timezone": "US/Pacific"
  },
  "link": "https://www.meetup.com/sfchihuahua/events/rxrchryznbjb/",
    "description": "<p>Come out to Stern Grove Dog Park on October 6th for our Halloween Meetup! Costumes encouraged for the Chihuahuas and the wonderful people who serve these little beasts!</p> <p>We will bring water and light snacks.</p> <p>As always, there will be dogs from local rescues looking for forever homes. We will send a follow-up email with the pics and bios. PLEASE PLEASE PLEASE tell friends and families about these adorable creatures. They promise to fill their peoples' lives with love, laughs and life long adoration.</p> <p>PLEASE remember that Stern Grove is the home to many animals and among those are coyotes. We ask that you walk your dogs to the Meetup location on leash. And we ask that if you dog is a wanderer that you please keep him or her on leash. We want to make sure NO DOG goes into the hills. That is where the coyotes have their dens. Do not let your dog venture off.</p> ",
      "how_to_find_us": "Look for the sea of Chis, Chi-mixes and other adorable little dogs in the middle of the dog park!",
        "visibility": "public",
          "member_pay_fee": false
},
{
  "created": 1569258169000,
    "duration": 10800000,
      "id": "265096595",
        "name": "Everyone Loves a Corgi at Spark Social",
          "date_in_series_pattern": false,
            "status": "upcoming",
              "time": 1572717600000,
                "local_date": "2019-11-02",
                  "local_time": "11:00",
                    "updated": 1569283927000,
                      "utc_offset": -25200000,
                        "waitlist_count": 0,
                          "yes_rsvp_count": 11,
                            "group": {
    "created": 1481474872000,
      "name": "Everyone Loves a Corgi",
        "id": 21547815,
          "join_mode": "approval",
            "lat": 37.77000045776367,
              "lon": -122.38999938964844,
                "urlname": "EveryoneCorg",
                  "who": "Members",
                    "localized_location": "San Francisco, CA",
                      "state": "CA",
                        "country": "us",
                          "region": "en_US",
                            "timezone": "US/Pacific"
  },
  "link": "https://www.meetup.com/EveryoneCorg/events/265096595/",
    "description": "<p>Spark Social has invited us back in November to fill a slot on their Fall event calendar. We always love the Spark/Quad combo...hope you can make it!</p> <p>We'll be in the blue tent area as usual, and plan to head over to the NEW Mission Bay dog park next to Azure apartments afterwards where the Corgs can escape the crowds and get their frap on!</p> <p>We'll also plan on doing the group photo at 1:00pm at the front entrance of Spark.</p> <p>You are welcome to bring guests, we turned that option off to allow us to better track how many Corgs will be at the event. Hope everyone can join us!</p> ",
      "visibility": "public",
        "member_pay_fee": false
},
{
  "created": 1568649411000,
    "duration": 7200000,
      "id": "264896451",
        "name": "Lands End Holiday Hike",
          "rsvp_limit": 50,
            "date_in_series_pattern": false,
              "status": "upcoming",
                "time": 1576954800000,
                  "local_date": "2019-12-21",
                    "local_time": "11:00",
                      "updated": 1568649411000,
                        "utc_offset": -28800000,
                          "waitlist_count": 0,
                            "yes_rsvp_count": 22,
                              "group": {
    "created": 1481474872000,
      "name": "Everyone Loves a Corgi",
        "id": 21547815,
          "join_mode": "approval",
            "lat": 37.77000045776367,
              "lon": -122.38999938964844,
                "urlname": "EveryoneCorg",
                  "who": "Members",
                    "localized_location": "San Francisco, CA",
                      "state": "CA",
                        "country": "us",
                          "region": "en_US",
                            "timezone": "US/Pacific"
  },
  "link": "https://www.meetup.com/EveryoneCorg/events/264896451/",
    "description": "<p>We did this last year, and this is quickly becoming a new holiday tradition for our group. This will be our third year doing this hike and the views along this trail are absolutely breathtaking, and they always remind me of how much I love SF!</p> <p>This is a well traveled trail, and is easy to moderate in difficulty and is about 3.5 miles round trip. Dogs need to remain on leash on the trails.</p> <p>IMPORTANT NOTE:</p> <p>By RSVP'ing YES for this event, you are agreeing to the following:</p> <p>1. Maintain oversight of your dogs and their welfare for the duration of the event.</p> <p>2. Keep your dogs on-leash for the duration of the hike.</p> <p>3. Release the organizers of this event of any liabilities for damages or injuries incurred by you or your dogs at the event.</p> ",
      "visibility": "public",
        "member_pay_fee": false
},
{
  "created": 1496272585000,
    "id": "bldsfnyznbhb",
      "name": "Saturday French Bulldog Meetup at Stern Grove",
        "date_in_series_pattern": false,
          "status": "upcoming",
            "time": 1570296600000,
              "local_date": "2019-10-05",
                "local_time": "10:30",
                  "updated": 1496272585000,
                    "utc_offset": -25200000,
                      "waitlist_count": 0,
                        "yes_rsvp_count": 7,
                          "venue": {
    "id": 22758672,
      "name": "Sigmund Stern grove ",
        "lat": 37.77711868286133,
          "lon": -122.41963958740234,
            "repinned": false,
              "address_1": "Vale ave. off of Sloat blvd",
                "city": "San Francisco",
                  "country": "us",
                    "localized_country_name": "USA",
                      "zip": "",
                        "state": "CA"
  },
  "group": {
    "created": 1262240897000,
      "name": "San Francisco French Bulldog Meetup",
        "id": 1575102,
          "join_mode": "open",
            "lat": 37.790000915527344,
              "lon": -122.41999816894531,
                "urlname": "French-Bulldog-Meetup",
                  "who": "Frenchie Enthusiasts/Parents",
                    "localized_location": "San Francisco, CA",
                      "state": "CA",
                        "country": "us",
                          "region": "en_US",
                            "timezone": "US/Pacific"
  },
  "link": "https://www.meetup.com/French-Bulldog-Meetup/events/bldsfnyznbhb/",
    "description": "<p>This is a great park with open space and real grass to run on! let's meet at 10:30. There is a water fountain for the dogs. The entrance is on Vale ave. off of Sloat blvd. go down the hill and there is usually ample parking. See everyone there.</p> ",
      "visibility": "public",
        "member_pay_fee": false
}
]
}

export default data;